let isAuthenticatedDoctor = false;
let currentRole = 'patient';
let isAccessGranted = false;

const patientDocuments = [
    { title: "Blood Analysis (HbA1c & Lipid Panel)", source: "Patient Uploaded", date: "15 Aug 2026" }
];
const doctorTips = [];

// Multi-Language Translation Map (10 Major Indian Languages)
const i18n = {
    en: {
        nav_home: "Platform",
        nav_services: "Our Services",
        nav_assessment: "Daily Assessment",
        nav_vault: "Digital Vault",
        nav_bot: "MediBot AI",
        nav_doctor: "Doctor Portal",
        btn_login: "Login / Access",
        hero_badge: "AI-Driven Health Records",
        hero_title1: "Intelligent Health",
        hero_title2: "Vault & Emergency AI",
        hero_desc: "Organize medical histories, take targeted daily AI assessments based on report findings, trigger emergency symptom escalations, and grant consent-controlled access to physicians.",
        btn_start_assessment: "Start Daily Assessment",
        btn_medibot: "Emergency MediBot",
        services_title: "MediVault AI Core Services",
        services_subtitle: "Modular, secure, and emergency-ready digital health infrastructure.",
        assess_title: "AI Daily Health Assessment",
        assess_subtitle: "Personalized 2-3 questions generated by analyzing your uploaded lab reports & medical history.",
        vault_title: "Patient Health Vault",
        vault_subtitle: "Manage encrypted documents and grant selective doctor access permissions",
        btn_upload: "Upload Medical Report",
        grant_title: "Grant Explicit Access to Doctor",
        grant_subtitle: "Only doctors with explicit access can view your health vault.",
        docs_title: "Your Encrypted Documents"
    },
    hi: {
        nav_home: "प्लेटफ़ॉर्म",
        nav_services: "हमारी सेवाएं",
        nav_assessment: "दैनिक मूल्यांकन",
        nav_vault: "डिजिटल वॉल्ट",
        nav_bot: "मेडीबॉट AI",
        nav_doctor: "डॉक्टर पोर्टल",
        btn_login: "लॉगिन / प्रवेश",
        hero_badge: "AI-संचालित स्वास्थ्य रिकॉर्ड",
        hero_title1: "बुद्धिमान स्वास्थ्य",
        hero_title2: "वॉल्ट और आपातकालीन AI",
        hero_desc: "चिकित्सा इतिहास प्रबंधित करें, रिपोर्ट के आधार पर दैनिक AI मूल्यांकन लें और डॉक्टरों को अनुमति दें।",
        btn_start_assessment: "दैनिक मूल्यांकन शुरू करें",
        btn_medibot: "आपातकालीन मेडीबॉट",
        services_title: "मेडीबॉट मुख्य सेवाएं",
        services_subtitle: "सुरक्षित और आपातकालीन डिजिटल स्वास्थ्य अवसंरचना।",
        assess_title: "AI दैनिक स्वास्थ्य मूल्यांकन",
        assess_subtitle: "आपकी मेडिकल रिपोर्ट के विश्लेषण से उत्पन्न 2-3 व्यक्तिगत प्रश्न।",
        vault_title: "मरीज़ स्वास्थ्य वॉल्ट",
        vault_subtitle: "एन्क्रिप्टेड दस्तावेज़ प्रबंधित करें और डॉक्टर को अनुमति दें",
        btn_upload: "मेडिकल रिपोर्ट अपलोड करें",
        grant_title: "डॉक्टर को अनुमति दें",
        grant_subtitle: "केवल आपकी अनुमति वाले डॉक्टर ही वॉल्ट देख सकते हैं।",
        docs_title: "आपके दस्तावेज़"
    },
    bn: {
        nav_home: "প্ল্যাটফর্ম",
        nav_services: "আমাদের পরিষেবা",
        nav_assessment: "দৈনিক মূল্যায়ন",
        nav_vault: "ডিজিটাল ভল্ট",
        nav_bot: "মেডিবট AI",
        nav_doctor: "ডাক্তার পোর্টাল",
        btn_login: "লগইন / অ্যাক্সেস",
        hero_badge: "AI-চালিত স্বাস্থ্য রেকর্ড",
        hero_title1: "বুদ্ধিমান স্বাস্থ্য",
        hero_title2: "ভল্ট ও জরুরি AI",
        hero_desc: "আপনার স্বাস্থ্যের বিবরণ এবং রিপোর্ট বিশ্লেষণ করে দৈনিক মূল্যায়ন গ্রহণ করুন।",
        btn_start_assessment: "মূল্যায়ন শুরু করুন",
        btn_medibot: "জরুরি মেডিবট",
        services_title: "প্রধান পরিষেবাসমূহ",
        services_subtitle: "নিরাপদ এবং জরুরি ডিজিটাল স্বাস্থ্য ব্যবস্থা।",
        assess_title: "AI দৈনিক স্বাস্থ্য মূল্যায়ন",
        assess_subtitle: "আপনার মেডিকেল রিপোর্টের উপর ভিত্তি করে ৩টি প্রশ্ন।",
        vault_title: "রোগীর হেলথ ভল্ট",
        vault_subtitle: "সুরক্ষিত নথিপত্র পরিচালনা করুন",
        btn_upload: "রিপোর্ট আপলোড করুন",
        grant_title: "ডাক্তারকে অ্যাক্সেস দিন",
        grant_subtitle: "শুধুমাত্র অনুমোদিত ডাক্তাররাই আপনার রেকর্ড দেখতে পাবেন।",
        docs_title: "আপনার নথিপত্র"
    },
    ta: {
        nav_home: "தளம்",
        nav_services: "எங்கள் சேவைகள்",
        nav_assessment: "தினசரி மதிப்பீடு",
        nav_vault: "டிஜிட்டல் வால்ட்",
        nav_bot: "மேடிபாட் AI",
        nav_doctor: "மருத்துவர் தளம்",
        btn_login: "உள்நுழைவு",
        hero_badge: "AI சுகாதார பதிவுகள்",
        hero_title1: "நுண்ணறிவு ஆரோக்கியம்",
        hero_title2: "வால்ட் & அவசர AI",
        hero_desc: "மருத்துவ அறிக்கைகளின் அடிப்படையில் தினசரி AI மதிப்பீட்டைப் பெறுங்கள்.",
        btn_start_assessment: "மதிப்பீட்டைத் தொடங்கு",
        btn_medibot: "அவசர மேடிபாட்",
        services_title: "முக்கிய சேவைகள்",
        services_subtitle: "பாதுகாப்பான டிஜிட்டல் சுகாதார தளம்.",
        assess_title: "தினசரி AI சுகாதார மதிப்பீடு",
        assess_subtitle: "அறிக்கைகளின் அடிப்படையில் 2-3 கேள்விகள்.",
        vault_title: "நோயாளி சுகாதார பெட்டகம்",
        vault_subtitle: "பாதுகாப்பான ஆவண மேலாண்மை",
        btn_upload: "அறிக்கையை பதிவேற்று",
        grant_title: "மருத்துவருக்கு அனுமதி வழங்கு",
        grant_subtitle: "அனுமதி பெற்ற மருத்துவர்கள் மட்டுமே பார்க்க முடியும்.",
        docs_title: "உங்கள் ஆவணங்கள்"
    },
    te: {
        nav_home: "ప్లాట్‌ఫారమ్",
        nav_services: "మా సేవలు",
        nav_assessment: "రోజువారీ అంచనా",
        nav_vault: "డిజిటల్ వాల్ట్",
        nav_bot: "మెడిబాట్ AI",
        nav_doctor: "డాక్టర్ పోర్టల్",
        btn_login: "లాగిన్",
        hero_badge: "AI ఆరోగ్య రికార్డులు",
        hero_title1: "ఇంటెలిజెంట్ హెల్త్",
        hero_title2: "వాల్ట్ & ఎమర్జెన్సీ AI",
        hero_desc: "మీ నివేదికల ఆధారంగా రోజువారీ AI ఆరోగ్య పరీక్షలను నిర్వహించండి.",
        btn_start_assessment: "అంచనా ప్రారంభించండి",
        btn_medibot: "ఎమర్జెన్సీ మెడిబాట్",
        services_title: "ప్రధాన సేవలు",
        services_subtitle: "సురక్షితమైన డిజిటల్ ఆరోగ్య విధానం.",
        assess_title: "AI రోజువారీ ఆరోగ్య పరీక్ష",
        assess_subtitle: "రిపోర్టుల ఆధారంగా తయారు చేసిన 2-3 ప్రశ్నలు.",
        vault_title: "పేషెంట్ హెల్త్ వాల్ట్",
        vault_subtitle: "రక్షిత పత్రాల నిర్వాహణ",
        btn_upload: "రిపోర్ట్ అప్‌లోడ్ చేయండి",
        grant_title: "డాక్టర్‌కు యాక్సెస్ ఇవ్వండి",
        grant_subtitle: "అనుమతించిన డాక్టర్లు మాత్రమే చూడగలరు.",
        docs_title: "మీ పత్రాలు"
    },
    mr: {
        nav_home: "प्लॅटफॉर्म",
        nav_services: "आमच्या सेवा",
        nav_assessment: "दैनंदिन मूल्यमापन",
        nav_vault: "डिजिटल व्हॉल्ट",
        nav_bot: "मेडीबॉट AI",
        nav_doctor: "डॉक्टर पोर्टल",
        btn_login: "लॉगिन",
        hero_badge: "AI-संचालित आरोग्य नोंदी",
        hero_title1: "स्मार्ट आरोग्य",
        hero_title2: "व्हॉल्ट आणि आणीबाणी AI",
        hero_desc: "वैद्यकीय अहवालांच्या आधारे दैनंदिन AI आरोग्य तपासणी करा.",
        btn_start_assessment: "चाचणी सुरू करा",
        btn_medibot: "आणीबाणी मेडीबॉट",
        services_title: "मुख्य सेवा",
        services_subtitle: "सुरक्षित डिजिटल आरोग्य यंत्रणा.",
        assess_title: "AI दैनंदिन आरोग्य चाचणी",
        assess_subtitle: "तुमच्या अहवालांवर आधारित 2-3 प्रश्न.",
        vault_title: "रुग्ण आरोग्य व्हॉल्ट",
        vault_subtitle: "सुरक्षित कागदपत्रे व्यवस्थापन",
        btn_upload: "अहवाल अपलोड करा",
        grant_title: "डॉक्टरांना परवानगी द्या",
        grant_subtitle: "फक्त परवानगी असलेले डॉक्टरच व्हॉल्ट पाहू शकतात.",
        docs_title: "तुमची कागदपत्रे"
    },
    gu: {
        nav_home: "પ્લેટફોર્મ",
        nav_services: "અમારી સેવાઓ",
        nav_assessment: "દૈનિક મૂલ્યાંકન",
        nav_vault: "ડિજિટલ વૉલ્ટ",
        nav_bot: "મેડીબોટ AI",
        nav_doctor: "ડૉક્ટર પોર્ટલ",
        btn_login: "લૉગિન",
        hero_badge: "AI હેલ્થ રેકોર્ડ્સ",
        hero_title1: "ઇન્ટેલિજન્ટ હેલ્થ",
        hero_title2: "વૉલ્ટ અને ઇમરજન્સી AI",
        hero_desc: "રિપોર્ટના આધારે દૈનિક AI સવાલ-જવાબ સાથે સ્વાસ્થ્ય ચકાસો.",
        btn_start_assessment: "મૂલ્યાંકન શરૂ કરો",
        btn_medibot: "ઇમરજન્સી મેડીબોટ",
        services_title: "મુખ્ય સેવાઓ",
        services_subtitle: "સુરક્ષિત ડિજિટલ હેલ્થ સિસ્ટમ.",
        assess_title: "AI દૈનિક હેલ્થ ચેક-ઇન",
        assess_subtitle: "તમારા મેડિકલ રિપોર્ટ આધારિત પ્રશ્નો.",
        vault_title: "પેશન્ટ હેલ્થ વૉલ્ટ",
        vault_subtitle: "સુરક્ષિત દસ્તાવેજ સંચાલન",
        btn_upload: "રિપોર્ટ અપલોડ કરો",
        grant_title: "ડૉક્ટરને ઍક્સેસ આપો",
        grant_subtitle: "માત્ર મંજૂર થયેલ ડૉક્ટર જ જોઈ શકશે.",
        docs_title: "તમારા દસ્તાવેજો"
    },
    kn: {
        nav_home: "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್",
        nav_services: "ನಮ್ಮ ಸೇವೆಗಳು",
        nav_assessment: "ದೈನಂದಿನ ಮೌಲ್ಯಮಾಪನ",
        nav_vault: "ಡಿಜಿಟಲ್ ವಾಲ್ಟ್",
        nav_bot: "ಮೆಡಿಬಾಟ್ AI",
        nav_doctor: "ವೈದ್ಯರ ಪೋರ್ಟಲ್",
        btn_login: "ಲಾಗಿನ್",
        hero_badge: "AI ಆರೋಗ್ಯ ದಾಖಲೆಗಳು",
        hero_title1: "ಬುದ್ಧಿವಂತ ಆರೋಗ್ಯ",
        hero_title2: "ವಾಲ್ಟ್ ಮತ್ತು ತುರ್ತು AI",
        hero_desc: "ವರದಿಗಳ ಆಧಾರದ ಮೇಲೆ ದೈನಂದಿನ AI ಆರೋಗ್ಯ ಮೌಲ್ಯಮಾಪನ ಪಡೆಯಿರಿ.",
        btn_start_assessment: "ಮೌಲ್ಯಮಾಪನ ಪ್ರಾರಂಭಿಸಿ",
        btn_medibot: "ತುರ್ತು ಮೆಡಿಬಾಟ್",
        services_title: "ಮುಖ್ಯ ಸೇವೆಗಳು",
        services_subtitle: "ಸುರಕ್ಷಿತ ಡಿಜಿಟಲ್ ಆರೋಗ್ಯ ವ್ಯವಸ್ಥೆ.",
        assess_title: "AI ದೈನಂದಿನ ಆರೋಗ್ಯ ಮೌಲ್ಯಮಾಪನ",
        assess_subtitle: "ಮೆಡಿಕಲ್ ವರದಿಗಳ ಆಧಾರದ 2-3 ಪ್ರಶ್ನೆಗಳು.",
        vault_title: "ರೋಗಿಯ ಆರೋಗ್ಯ ವಾಲ್ಟ್",
        vault_subtitle: "ಸುರಕ್ಷಿತ ದಾಖಲೆ ನಿರ್ವಹಣೆ",
        btn_upload: "ವರದಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
        grant_title: "ವೈದ್ಯರಿಗೆ ಅನುಮತಿ ನೀಡಿ",
        grant_subtitle: "ಅನುಮೋದಿತ ವೈದ್ಯರು ಮಾತ್ರ ವೀಕ್ಷಿಸಬಹುದು.",
        docs_title: "ನಿಮ್ಮ ದಾಖಲೆಗಳು"
    },
    ml: {
        nav_home: "പ്ലാറ്റ്‌ഫോം",
        nav_services: "ഞങ്ങളുടെ സേവനങ്ങൾ",
        nav_assessment: "ദിനാധിഷ്ഠിത വിലയിരുത്തൽ",
        nav_vault: "ഡിജിറ്റൽ വോൾട്ട്",
        nav_bot: "മെഡിബോട്ട് AI",
        nav_doctor: "ഡോക്ടർ പോർട്ടൽ",
        btn_login: "ലോഗിൻ",
        hero_badge: "AI ആരോഗ്യ രേഖകൾ",
        hero_title1: "ഇന്റലിജന്റ് ഹെൽത്ത്",
        hero_title2: "വോൾട്ട് & എമർജൻസി AI",
        hero_desc: "റിപ്പോർട്ടുകളുടെ അടിസ്ഥാനത്തിൽ പ്രതിദിന AI പരിശോധന നടത്തുക.",
        btn_start_assessment: "പരിശോധന ആരംഭിക്കുക",
        btn_medibot: "എമർജൻസി മെഡിബോട്ട്",
        services_title: "പ്രധാന സേവനങ്ങൾ",
        services_subtitle: "ഡിജിറ്റൽ ആരോഗ്യ സംവിധാനം.",
        assess_title: "AI പ്രതിദിന ആരോഗ്യ വിലയിരുത്തൽ",
        assess_subtitle: "മെഡിക്കൽ റിപ്പോർട്ടുകൾ വിശകലനം ചെയ്തുള്ള ചോദ്യങ്ങൾ.",
        vault_title: "പേഷ്യന്റ് ഹെൽത്ത് വോൾട്ട്",
        vault_subtitle: "സുരക്ഷിത രേഖാ മാനേജ്മെന്റ്",
        btn_upload: "റിപ്പോർട്ട് അപ്‌ലോഡ് ചെയ്യുക",
        grant_title: "ഡോക്ടർക്ക് അനുമതി നൽകുക",
        grant_subtitle: "അനുമതിയുള്ള ഡോക്ടർമാർക്ക് മാത്രം പ്രവേശനം.",
        docs_title: "നിങ്ങളുടെ രേഖകൾ"
    },
    pa: {
        nav_home: "ਪਲੇਟਫਾਰਮ",
        nav_services: "ਸਾਡੀਆਂ ਸੇਵਾਵਾਂ",
        nav_assessment: "ਰੋਜ਼ਾਨਾ ਮੁਲਾਂਕਣ",
        nav_vault: "ਡਿਜੀਟਲ ਵਾਲਟ",
        nav_bot: "ਮੈਡੀਬੋਟ AI",
        nav_doctor: "ਡਾਕਟਰ ਪੋਰਟਲ",
        btn_login: "ਲੌਗਇਨ",
        hero_badge: "AI ਸਿਹਤ ਰਿਕਾਰਡ",
        hero_title1: "ਸਮਾਰਟ ਸਿਹਤ",
        hero_title2: "ਵਾਲਟ ਅਤੇ ਐਮਰਜੈਂਸੀ AI",
        hero_desc: "ਮੈਡੀਕਲ ਰਿਪੋਰਟਾਂ ਦੇ ਆਧਾਰ 'ਤੇ ਰੋਜ਼ਾਨਾ AI ਸਿਹਤ ਦੀ ਜਾਂਚ ਕਰੋ।",
        btn_start_assessment: "ਮੁਲਾਂਕਣ ਸ਼ੁਰੂ ਕਰੋ",
        btn_medibot: "ਐਮਰਜੈਂਸੀ ਮੈਡੀਬੋਟ",
        services_title: "ਮੁੱਖ ਸੇਵਾਵਾਂ",
        services_subtitle: "ਸੁਰੱਖਿਅਤ ਡਿਜੀਟਲ ਸਿਹਤ ਪ੍ਰਣਾਲੀ।",
        assess_title: "AI ਰੋਜ਼ਾਨਾ ਸਿਹਤ ਜਾਂਚ",
        assess_subtitle: "ਤੁਹਾਡੀ ਰਿਪੋਰਟ 'ਤੇ ਆਧਾਰਿਤ 2-3 ਸਵਾਲ।",
        vault_title: "ਮਰੀਜ਼ ਸਿਹਤ ਵਾਲਟ",
        vault_subtitle: "ਸੁਰੱਖਿਅਤ ਦਸਤਾਵੇਜ਼ ਪ੍ਰਬੰਧਨ",
        btn_upload: "ਰਿਪੋਰਟ ਅੱਪਲੋਡ ਕਰੋ",
        grant_title: "ਡਾਕਟਰ ਨੂੰ ਇਜਾਜ਼ਤ ਦਿਓ",
        grant_subtitle: "ਸਿਰਫ਼ ਮਨਜ਼ੂਰਸ਼ੁਦਾ ਡਾਕਟਰ ਹੀ ਦੇਖ ਸਕਦੇ ਹਨ।",
        docs_title: "ਤੁਹਾਡੇ ਦਸਤਾਵੇਜ਼"
    }
};

window.addEventListener('DOMContentLoaded', () => {
    lucide.createIcons();
});

function changeLanguage(langKey) {
    const dictionary = i18n[langKey] || i18n.en;
    document.querySelectorAll('[data-lang]').forEach(el => {
        const key = el.getAttribute('data-lang');
        if (dictionary[key]) {
            el.textContent = dictionary[key];
        }
    });
}

function attemptDoctorAccess() {
    if (isAuthenticatedDoctor) {
        switchTab('doctor');
    } else {
        setLoginRole('doctor');
        showLogin();
    }
}

function closeLoginModal() {
    document.getElementById('view-login').classList.add('hidden');
}

function showLogin() {
    document.getElementById('view-login').classList.remove('hidden');
}

function switchTab(tabId) {
    if (tabId === 'doctor' && !isAuthenticatedDoctor) {
        attemptDoctorAccess();
        return;
    }

    const tabs = ['home', 'services', 'assessment', 'locker', 'chatbot', 'doctor'];
    tabs.forEach(tab => {
        const el = document.getElementById(`view-${tab}`);
        if (el) el.classList.add('hidden');
    });

    const targetView = document.getElementById(`view-${tabId}`);
    if (targetView) targetView.classList.remove('hidden');
    window.scrollTo({ top: 0, behavior: 'smooth' });
}

function setLoginRole(role) {
    currentRole = role;
    const patientBtn = document.getElementById('roleBtnPatient');
    const doctorBtn = document.getElementById('roleBtnDoctor');
    const doctorField = document.getElementById('doctorIdFieldGroup');
    const title = document.getElementById('loginHeaderTitle');
    const sub = document.getElementById('loginSubText');

    if (role === 'doctor') {
        doctorBtn.className = "flex-1 py-2 text-xs font-bold rounded-xl bg-white text-emerald-700 shadow-sm transition-all flex items-center justify-center space-x-1.5";
        patientBtn.className = "flex-1 py-2 text-xs font-bold rounded-xl text-slate-500 hover:text-slate-800 transition-all flex items-center justify-center space-x-1.5";
        doctorField.classList.remove('hidden');
        title.textContent = "Doctor Workspace Login";
        sub.textContent = "Enter your physician license ID to open protected patient records.";
    } else {
        patientBtn.className = "flex-1 py-2 text-xs font-bold rounded-xl bg-white text-emerald-700 shadow-sm transition-all flex items-center justify-center space-x-1.5";
        doctorBtn.className = "flex-1 py-2 text-xs font-bold rounded-xl text-slate-500 hover:text-slate-800 transition-all flex items-center justify-center space-x-1.5";
        doctorField.classList.add('hidden');
        title.textContent = "Patient Workspace Login";
        sub.textContent = "Access encrypted records, consent sharing, and daily AI check-ins.";
    }
}

function handleLoginSubmit(e) {
    e.preventDefault();
    closeLoginModal();

    if (currentRole === 'doctor') {
        isAuthenticatedDoctor = true;
        const authContainer = document.getElementById('authStatusContainer');
        if (authContainer) {
            authContainer.innerHTML = `
                <div class="flex items-center space-x-2">
                    <span class="bg-emerald-100 text-emerald-800 text-xs font-bold px-3 py-1.5 rounded-full border border-emerald-200">
                        Dr. Alok Sharma (Verified)
                    </span>
                </div>
            `;
        }
        switchTab('doctor');
    } else {
        switchTab('locker');
    }
}

function logoutDoctor() {
    isAuthenticatedDoctor = false;
    window.location.reload();
}

function handleAssessmentSubmit(e) {
    e.preventDefault();
    const resultCard = document.getElementById('assessmentResultCard');
    if (resultCard) resultCard.classList.remove('hidden');
}

function sendAccessRequest() {
    const input = document.getElementById('doctorGrantInput');
    const docName = input ? input.value.trim() : '';
    if (!docName) return;

    const msg = document.getElementById('grantStatusMsg');
    if (msg) {
        msg.classList.remove('hidden');
        msg.textContent = `✓ Access permission issued to ${docName}`;
    }
    const docList = document.getElementById('authorizedDoctorsList');
    if (docList) {
        docList.innerHTML = `<span class="bg-amber-100 text-amber-800 px-2.5 py-1 rounded-md font-semibold text-[11px]">${docName} (Pending Authorization)</span>`;
    }
}

function acceptAccessRequest() {
    isAccessGranted = true;
    const banner = document.getElementById('doctorAccessRequestBanner');
    if (banner) banner.classList.add('hidden');

    const badge = document.getElementById('accessStatusBadge');
    if (badge) {
        badge.className = "bg-emerald-100 text-emerald-800 font-bold text-xs px-3 py-1 rounded-full";
        badge.textContent = "Access: Active & Verified";
    }
    renderDocumentLists();
}

function handlePatientFileUpload(e) {
    const file = e.target.files[0];
    if (file) {
        patientDocuments.unshift({ title: file.name, source: "Patient Uploaded", date: "Just Now" });
        
        const activeDocLabel = document.getElementById('activeDocName');
        if (activeDocLabel) activeDocLabel.textContent = ` ${file.name} (Just Uploaded)`;
        
        renderDocumentLists();
    }
}

function handleDoctorFileUpload(e) {
    const file = e.target.files[0];
    if (file) {
        patientDocuments.unshift({ title: file.name, source: "Doctor Prescribed", date: "Just Now" });
        renderDocumentLists();
    }
}

function sendDoctorTip() {
    const input = document.getElementById('doctorTipInput');
    const tipText = input ? input.value.trim() : '';
    if (!tipText) return;

    doctorTips.unshift({ text: tipText, doctor: "Dr. Alok Sharma", time: "Just Now" });
    if (input) input.value = '';

    const tipsContainer = document.getElementById('doctorTipsContainer');
    if (tipsContainer) {
        tipsContainer.innerHTML = doctorTips.map(t => `
            <div class="p-3 bg-emerald-50 border border-emerald-100 rounded-xl">
                <p class="font-bold text-slate-800 text-[11px]">${t.doctor} (${t.time})</p>
                <p class="text-slate-600 text-[11px] mt-0.5">${t.text}</p>
            </div>
        `).join('');
    }
}

function renderDocumentLists() {
    const patientList = document.getElementById('patientDocumentList');
    if (patientList) {
        patientList.innerHTML = patientDocuments.map(doc => `
            <div class="flex items-center justify-between p-3.5 rounded-xl bg-slate-50 text-xs">
                <div class="flex items-center space-x-3">
                    <i data-lucide="file-text" class="w-4 h-4 text-emerald-600"></i>
                    <div>
                        <p class="font-bold text-slate-800">${doc.title}</p>
                        <p class="text-slate-400">${doc.date}</p>
                    </div>
                </div>
                <span class="text-[10px] ${doc.source.includes('Doctor') ? 'bg-emerald-100 text-emerald-800' : 'bg-emerald-50 text-emerald-700'} font-bold px-2.5 py-1 rounded-full">${doc.source}</span>
            </div>
        `).join('');
    }

    const doctorList = document.getElementById('doctorViewReportsList');
    if (doctorList) {
        if (!isAccessGranted) {
            doctorList.innerHTML = `<div class="p-4 bg-slate-50 rounded-2xl text-xs text-slate-500 italic text-center">Click "Accept Access & View Vault" above to unlock patient records.</div>`;
        } else {
            doctorList.innerHTML = patientDocuments.map(doc => `
                <div class="flex items-center justify-between p-3.5 rounded-xl bg-slate-50 text-xs">
                    <div class="flex items-center space-x-3">
                        <i data-lucide="file-text" class="w-4 h-4 text-emerald-600"></i>
                        <div>
                            <p class="font-bold text-slate-800">${doc.title}</p>
                            <p class="text-slate-400">${doc.date}</p>
                        </div>
                    </div>
                    <span class="text-[10px] bg-emerald-100 text-emerald-800 font-bold px-2.5 py-1 rounded-full">Encrypted & Verified</span>
                </div>
            `).join('');
        }
    }
    lucide.createIcons();
}

function quickSymptom(text) {
    const input = document.getElementById('chatInput');
    if (input) {
        input.value = text;
        handleChatSubmit(new Event('submit'));
    }
}

function handleChatSubmit(e) {
    e.preventDefault();
    const input = document.getElementById('chatInput');
    const text = input ? input.value.trim() : '';
    if (!text) return;

    const chatContainer = document.getElementById('chatContainer');
    chatContainer.insertAdjacentHTML('beforeend', `
        <div class="flex justify-end">
            <div class="max-w-[80%] rounded-2xl p-4 text-xs leading-relaxed bg-emerald-600 text-white rounded-br-none">
                ${text}
            </div>
        </div>
    `);
    if (input) input.value = '';
    chatContainer.scrollTop = chatContainer.scrollHeight;

    const emergencyKeywords = ['chest pain', 'heart attack', 'cannot breathe', 'fainting', 'unconscious', 'severe bleeding', 'stroke'];
    const isEmergency = emergencyKeywords.some(kw => text.toLowerCase().includes(kw));

    setTimeout(() => {
        if (isEmergency) {
            const alertBanner = document.getElementById('emergencyAlertBanner');
            if (alertBanner) alertBanner.classList.remove('hidden');

            chatContainer.insertAdjacentHTML('beforeend', `
                <div class="flex justify-start">
                    <div class="max-w-[80%] rounded-2xl p-4 text-xs leading-relaxed bg-red-50 border border-red-200 text-red-800 shadow-sm rounded-bl-none font-semibold">
                        🚨 URGENT EMERGENCY ESCALATION: High-risk distress symptoms detected. Dr. Alok Sharma has been notified via priority SOS notification.
                    </div>
                </div>
            `);
        } else {
            chatContainer.insertAdjacentHTML('beforeend', `
                <div class="flex justify-start">
                    <div class="max-w-[80%] rounded-2xl p-4 text-xs leading-relaxed bg-white text-slate-800 border border-slate-100 shadow-sm rounded-bl-none">
                        Verified record context: Active prescription for Metformin 500mg daily. Latest HbA1c lab result: 6.8%.
                    </div>
                </div>
            `);
        }
        chatContainer.scrollTop = chatContainer.scrollHeight;
    }, 500);
}